@baseUrl = https://green-sg.herokuapp.com/api

//Get all users
GET {{baseUrl}}/getusers

###
//Post new user
POST {{baseUrl}}/postuser
Content-Type: application/json

{
  "username": "helloYahoo",
  "firstName": "Hello",
  "lastName": "Spring",
  "email": "hello@yahoo.com",
  "password": "hello"
}

