spring.datasource.url: jdbc:postgresql://${RDS_DB_NAME}:${RDS_PORT}/${RDS_DB_NAME}
spring.datasource.username: ${RDS_USERNAME}
spring.datasource.password: ${RDS_PASSWORD}
server.port: 5000
clientURL: https://project4-beryl.vercel.app/
